site_name: SMODERP2D
site_url:  https://github.com/storm-fsv-cvut/smoderp2d/
docs_dir:  docs
theme: 
  name: readthedocs
#  logo: img/qgis_plugin_icon.png
  features:
    - content.code.copy
use_directory_urls: false
nav:
    - 'index.md'
    - 'qgis.md'
    - 'grass.md'
    - 'arcgis.md'
markdown_extensions:
  - attr_list
  - md_in_html
  - toc:
      permalink:   
plugins:
  - glightbox
  - search
  - table-reader
