site_name: SMODERP2D
site_url:  https://github.com/storm-fsv-cvut/smoderp2d/
docs_dir:  docs
theme: 
  name: readthedocs
  features:
    - content.code.copy
use_directory_urls: false
nav:
    - 'index.md'
