site_name: SMODERP2D
site_url:  https://github.com/storm-fsv-cvut/smoderp2d/
docs_dir:  docs
theme: 
  name: readthedocs
  features:
    - content.code.copy
use_directory_urls: false
nav:
    - 'index.md'
    - 'qgis.md'
    - 'grass.md'
    - 'arcgis.md'
    - 'install.md'
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
